#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: '自己的学号'
      #password 密码
      password: '自己的密码'
      #address 地址，定位信息
      address: 中国江苏省南京市浦口区雨山路86号
      #email 接受通知消息的邮箱
      email: 邮箱@qq.com
      #serverchan Server酱的接口
      serverchan: 此处填写自己的server酱key，获取serverchan请参阅 http://sc.ftqq.com/
      #school 学校全称
      school: 南京审计大学
      #lon 经度 此处默认经纬度为沁园13栋
      lon: '118.619966'
      #lat 纬度
      lat: '32.070899'
      #abnormalReason 反馈信息
      abnormalReason: 36.5
      #photo 签到照片，不需要可不填，或者直接删除
      photo:
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #是否检查问题,true检查，false不检查
  check: true
  #附加信息组默认选项配置，没有可留空
  defaults:
  #附加信息组默认选项配置，按顺序，可留空
    - default:
        other: '36.3'
        title: 请填报体温
        value: 其它

